name: Python Application CI

on:
  push:
    branches: [ "main" ] # Trigger on pushes to main branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests to main branch
  workflow_dispatch: # Allow manual triggering from GitHub UI

jobs:
  lint-and-format:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Match Dockerfile Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black # Install linters and formatters

    - name: Lint with Flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check formatting with Black
      run: |
        black --check .

  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint-and-format # Run after linting and formatting checks
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest # Install pytest

    - name: Run Pytest
      run: |
        pytest tests/ # Explicitly point to tests directory
        # We will add actual tests in the next plan step.
